name: Build VSIX

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, reopened, synchronize]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          check-latest: true

      - name: Get Short SHA
        id: get-short-sha
        run: echo "sha=$(git rev-parse --short ${GITHUB_SHA})" >> $GITHUB_OUTPUT

      - name: Update the package version
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "\"version\": \"(\\d+\\.\\d+\\.\\d+)\""
          replace: "\"version\": \"$1-${{ steps.get-short-sha.outputs.sha }}\""
          include: "package.json"
          exclude: ".git"

      - name: Build the VSIX
        run:  |
          npm install
          npm run package

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: hello.vsix
          path: ./out/hello.vsix
          if-no-files-found: error

  release:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    needs: build
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Get Date String
        id: get-date-string
        run: echo "date_string=$(date +%Y-%m-%d)" >> $GITHUB_OUTPUT
    
      - name: Get package version
        id: get-package-version
        run: echo "package_version=$(cat package.json | jq -r '.version')" >> $GITHUB_OUTPUT

      - name: Get Short SHA
        id: get-short-sha
        run: echo "sha=$(git rev-parse --short ${GITHUB_SHA})" >> $GITHUB_OUTPUT

      - uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: v${{ steps.get-package-version.outputs.package_version }}-${{ steps.get-date-string.outputs.date_string }}+${{ steps.get-short-sha.outputs.sha }}
          tag_name: v${{ steps.get-package-version.outputs.package_version }}-${{ steps.get-date-string.outputs.date_string }}+${{ steps.get-short-sha.outputs.sha }}

      - uses: actions/download-artifact@v2
        with:
          name: hello.vsix

      - uses: actions/upload-release-asset@v1.0.2
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
            asset_content_type: application/octet-stream
            asset_name: hello.vsix
            asset_path: hello.vsix
            upload_url: ${{ steps.create_release.outputs.upload_url }}